apiVersion: v1
kind: Config
preferences: {}
clusters:
- name: keycloak-server
  cluster:
    certificate-authority: /etc/origin/master/ca.crt
    server: KEYCLOAK_URL/realms/master/protocol/openid-connect/ext/openshift-token-review/token-review
users:
- name: api-server
  user:
    client-certificate: /etc/origin/master/ca.crt
    client-key: /etc/origin/master/ca.key
current-context: authwebhook
contexts:
- context:
    cluster: keycloak-server
    user: api-server
  name: authwebhook
